#!/usr/bin/env bash
set -euo pipefail
# generate-publishers-readme.sh - Generate README.md for publishers directory
#
# Version: 1.0.0
# Purpose: Create provenance chain README with statistics and entity index for publishers
# Architecture: LLM-Control pattern with JSON I/O, following generate-query-batches-readme.sh pattern
# Compatibility: bash 3.2+ (no associative arrays)
#
# Exit codes:
#   0 - Success
#   2 - Invalid arguments or missing required paths
#   3 - No publisher files found


# ============================================================================
# ARGUMENT PARSING
# ============================================================================

project_path=""
json_output="false"
project_language="en"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-path)
      project_path="$2"
      shift 2
      ;;
    --json)
      json_output="true"
      shift
      ;;
    --language)
      project_language="$2"
      shift 2
      ;;
    *)
      echo "{\"success\": false, \"error\": \"Unknown argument: $1\"}" >&2
      exit 2
      ;;
  esac
done

# Validate required arguments
if [[ -z "$project_path" ]]; then
  echo "{\"success\": false, \"error\": \"Required argument: --project-path\"}" >&2
  exit 2
fi

# Validate project path exists
if [[ ! -d "$project_path" ]]; then
  echo "{\"success\": false, \"error\": \"Project path not found: $project_path\"}" >&2
  exit 2
fi

# ============================================================================
# SOURCE CENTRALIZED CONFIG
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Try to source entity-config.sh for DATA_SUBDIR
if [[ -f "${SCRIPT_DIR}/lib/entity-config.sh" ]]; then
  source "${SCRIPT_DIR}/lib/entity-config.sh"
  DATA_SUBDIR="$(get_data_subdir)"
else
  DATA_SUBDIR="data"
fi

# ============================================================================
# LANGUAGE TRANSLATION MAP
# ============================================================================

get_translation() {
  local key="$1"
  case "$project_language" in
    de)
      case "$key" in
        "Publishers") echo "Herausgeber" ;;
        "Statistics") echo "Statistiken" ;;
        "Mindmap") echo "Mindmap" ;;
        "Entity Index") echo "Entitätsindex" ;;
        "Provenance Chain") echo "Herkunftskette" ;;
        "Generated by") echo "Erstellt von" ;;
        "Metric") echo "Metrik" ;;
        "Value") echo "Wert" ;;
        "Publisher") echo "Herausgeber" ;;
        "Type") echo "Typ" ;;
        "Sources") echo "Quellen" ;;
        "Link") echo "Link" ;;
        "Total Publishers") echo "Herausgeber gesamt" ;;
        "Individuals") echo "Einzelpersonen" ;;
        "Organizations") echo "Organisationen" ;;
        "This directory contains") echo "Dieses Verzeichnis enthält" ;;
        "publisher profiles extracted from") echo "Herausgeberprofile extrahiert aus" ;;
        "research sources") echo "Forschungsquellen" ;;
        *) echo "$key" ;;
      esac
      ;;
    nl)
      case "$key" in
        "Publishers") echo "Uitgevers" ;;
        "Statistics") echo "Statistieken" ;;
        "Mindmap") echo "Mindmap" ;;
        "Entity Index") echo "Entiteitsindex" ;;
        "Provenance Chain") echo "Herkomst keten" ;;
        "Generated by") echo "Gegenereerd door" ;;
        "Metric") echo "Metriek" ;;
        "Value") echo "Waarde" ;;
        "Publisher") echo "Uitgever" ;;
        "Type") echo "Type" ;;
        "Sources") echo "Bronnen" ;;
        "Link") echo "Link" ;;
        "Total Publishers") echo "Totaal uitgevers" ;;
        "Individuals") echo "Individuen" ;;
        "Organizations") echo "Organisaties" ;;
        "This directory contains") echo "Deze map bevat" ;;
        "publisher profiles extracted from") echo "uitgeversprofielen geëxtraheerd uit" ;;
        "research sources") echo "onderzoeksbronnen" ;;
        *) echo "$key" ;;
      esac
      ;;
    fr)
      case "$key" in
        "Publishers") echo "Éditeurs" ;;
        "Statistics") echo "Statistiques" ;;
        "Mindmap") echo "Carte mentale" ;;
        "Entity Index") echo "Index des entités" ;;
        "Provenance Chain") echo "Chaîne de provenance" ;;
        "Generated by") echo "Généré par" ;;
        "Metric") echo "Métrique" ;;
        "Value") echo "Valeur" ;;
        "Publisher") echo "Éditeur" ;;
        "Type") echo "Type" ;;
        "Sources") echo "Sources" ;;
        "Link") echo "Lien" ;;
        "Total Publishers") echo "Total des éditeurs" ;;
        "Individuals") echo "Individus" ;;
        "Organizations") echo "Organisations" ;;
        "This directory contains") echo "Ce répertoire contient" ;;
        "publisher profiles extracted from") echo "profils d'éditeurs extraits de" ;;
        "research sources") echo "sources de recherche" ;;
        *) echo "$key" ;;
      esac
      ;;
    *)  # en default
      echo "$key"
      ;;
  esac
}

# ============================================================================
# PATH CONFIGURATION
# ============================================================================

publishers_base_dir="$project_path/08-publishers"
publishers_dir="$publishers_base_dir/$DATA_SUBDIR"

# Wikilink script path
if [[ -n "${CLAUDE_PLUGIN_ROOT:-}" ]]; then
  WIKILINK_SCRIPT="${CLAUDE_PLUGIN_ROOT}/scripts/generate-wikilink.sh"
else
  WIKILINK_SCRIPT="${SCRIPT_DIR}/generate-wikilink.sh"
fi

# Validate publishers directory exists
if [[ ! -d "$publishers_dir" ]]; then
  echo "{\"success\": false, \"error\": \"Publishers directory not found: $publishers_dir\"}" >&2
  exit 2
fi

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

# Extract YAML frontmatter from markdown file
extract_frontmatter() {
  local file="$1"
  sed -n '/^---$/,/^---$/p' "$file" | sed '1d;$d'
}

# Extract value from YAML frontmatter (simple key: value parsing)
get_frontmatter_value() {
  local file="$1"
  local key="$2"
  local result
  result="$(extract_frontmatter "$file" | grep "^${key}:" | sed "s/^${key}:[[:space:]]*//" | sed 's/^"//' | sed 's/"$//' || true)"
  echo "$result"
}

# Sanitize text for Mermaid mindmap nodes
sanitize_mindmap_label() {
  echo "$1" | sed 's/([^)]*)//g' | sed 's/[:\[\]"<>]//g' | sed 's/  */ /g' | sed 's/^ *//' | sed 's/ *$//'
}

# Generate wikilink using utility script or fallback
generate_wikilink() {
  local entity_dir="$1"
  local filename="$2"
  local display_name="${3:-}"

  local path="${entity_dir}/${DATA_SUBDIR}/${filename}"
  local fallback_link
  if [[ -n "$display_name" ]]; then
    fallback_link="[[$path|$display_name]]"
  else
    fallback_link="[[$path]]"
  fi

  if [[ -x "$WIKILINK_SCRIPT" ]]; then
    local wikilink_result
    if [[ -n "$display_name" ]]; then
      wikilink_result="$(bash "$WIKILINK_SCRIPT" --project-path "$project_path" --entity-dir "$entity_dir" --filename "$filename" --display-name "$display_name" 2>/dev/null || true)"
    else
      wikilink_result="$(bash "$WIKILINK_SCRIPT" --project-path "$project_path" --entity-dir "$entity_dir" --filename "$filename" 2>/dev/null || true)"
    fi

    if [[ -n "$wikilink_result" ]] && echo "$wikilink_result" | jq -e . >/dev/null 2>&1; then
      echo "$wikilink_result" | jq -r '.data.wikilink'
      return
    fi
  fi

  echo "$fallback_link"
}

# ============================================================================
# COLLECT PUBLISHER FILES
# ============================================================================

publisher_files=()
while IFS= read -r -d '' file; do
  publisher_files+=("$file")
done < <(find "$publishers_dir" -maxdepth 1 -name "publisher-*.md" -type f -print0 2>/dev/null | sort -z)

publisher_count="${#publisher_files[@]}"

if [[ "$publisher_count" -eq 0 ]]; then
  echo "{\"success\": false, \"error\": \"No publisher files found in $publishers_dir\"}" >&2
  exit 3
fi

# ============================================================================
# PARSE PUBLISHER METADATA (bash 3.2 compatible - no associative arrays)
# ============================================================================

# Track statistics
individual_count=0
organization_count=0
total_source_refs=0

# Use temp files for type grouping (bash 3.2 compatible)
TEMP_DIR="${TMPDIR:-/tmp}/publishers-readme-$$"
mkdir -p "$TEMP_DIR"
trap 'rm -rf "$TEMP_DIR"' EXIT

for publisher_file in "${publisher_files[@]}"; do
  publisher_filename="$(basename "$publisher_file" .md)"

  # Extract frontmatter values
  publisher_name="$(get_frontmatter_value "$publisher_file" "name")"
  if [[ -z "$publisher_name" ]]; then
    publisher_name="$(get_frontmatter_value "$publisher_file" "dc:title")"
  fi
  publisher_type="$(get_frontmatter_value "$publisher_file" "publisher_type")"
  if [[ -z "$publisher_type" ]]; then
    publisher_type="$(get_frontmatter_value "$publisher_file" "type")"
  fi

  # Count source references (source_ids array)
  source_ids="$(get_frontmatter_value "$publisher_file" "source_ids")"
  if [[ -n "$source_ids" ]]; then
    source_count="$(echo "$source_ids" | tr ',' '\n' | grep -c '[a-z]' || echo "0")"
    total_source_refs=$((total_source_refs + source_count))
  else
    source_count=0
  fi

  # Categorize by type
  if [[ -z "$publisher_type" ]]; then
    publisher_type="organization"
  fi

  case "$publisher_type" in
    individual|person|author)
      individual_count=$((individual_count + 1))
      publisher_type_normalized="individual"
      ;;
    *)
      organization_count=$((organization_count + 1))
      publisher_type_normalized="organization"
      ;;
  esac

  # Fallback name if empty
  if [[ -z "$publisher_name" ]]; then
    publisher_name="$publisher_filename"
  fi

  # Append publisher data to temp file
  echo "${publisher_filename}|${publisher_name}|${publisher_type_normalized}|${source_count}" >> "$TEMP_DIR/publishers_all"
done

# ============================================================================
# BUILD README CONTENT
# ============================================================================

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")"

# Get translated labels
LABEL_PUBLISHERS="$(get_translation "Publishers")"
LABEL_STATISTICS="$(get_translation "Statistics")"
LABEL_MINDMAP="$(get_translation "Mindmap")"
LABEL_ENTITY_INDEX="$(get_translation "Entity Index")"
LABEL_PROVENANCE="$(get_translation "Provenance Chain")"
LABEL_GENERATED_BY="$(get_translation "Generated by")"
LABEL_METRIC="$(get_translation "Metric")"
LABEL_VALUE="$(get_translation "Value")"
LABEL_PUBLISHER="$(get_translation "Publisher")"
LABEL_TYPE="$(get_translation "Type")"
LABEL_SOURCES="$(get_translation "Sources")"
LABEL_LINK="$(get_translation "Link")"
LABEL_TOTAL_PUBLISHERS="$(get_translation "Total Publishers")"
LABEL_INDIVIDUALS="$(get_translation "Individuals")"
LABEL_ORGANIZATIONS="$(get_translation "Organizations")"
LABEL_CONTAINS="$(get_translation "This directory contains")"
LABEL_EXTRACTED="$(get_translation "publisher profiles extracted from")"
LABEL_RESEARCH_SOURCES="$(get_translation "research sources")"

# Build Mermaid mindmap by type
mindmap_individuals=""
mindmap_organizations=""
entity_index=""

while IFS='|' read -r p_filename p_name p_type p_sources; do
  if [[ -n "$p_filename" ]]; then
    p_name_short="$(sanitize_mindmap_label "$p_name" | cut -c1-35)"

    # Group into type sections
    if [[ "$p_type" == "individual" ]]; then
      mindmap_individuals+="      $p_name_short"$'\n'
    else
      mindmap_organizations+="      $p_name_short"$'\n'
    fi

    # Generate wikilink for entity index
    publisher_wikilink="$(generate_wikilink "08-publishers" "$p_filename" "$p_name")"
    entity_index+="| $publisher_wikilink | $p_type | $p_sources |"$'\n'
  fi
done < "$TEMP_DIR/publishers_all"

# Build complete mindmap content
mindmap_content=""
if [[ -n "$mindmap_individuals" ]]; then
  mindmap_content+="    $LABEL_INDIVIDUALS"$'\n'
  mindmap_content+="$mindmap_individuals"
fi
if [[ -n "$mindmap_organizations" ]]; then
  mindmap_content+="    $LABEL_ORGANIZATIONS"$'\n'
  mindmap_content+="$mindmap_organizations"
fi

# ============================================================================
# WRITE README FILE
# ============================================================================

readme_path="$publishers_base_dir/README.md"

cat > "$readme_path" <<EOF
---
title: "${LABEL_PUBLISHERS} Overview"
generated_by: publisher-generator
generated_at: $timestamp
publisher_count: $publisher_count
individual_count: $individual_count
organization_count: $organization_count
source_refs_total: $total_source_refs
project_language: $project_language
---

# $LABEL_PUBLISHERS

$LABEL_CONTAINS $LABEL_EXTRACTED $LABEL_RESEARCH_SOURCES.

## $LABEL_PROVENANCE

\`\`\`mermaid
mindmap
  root(($LABEL_PUBLISHERS))
$mindmap_content\`\`\`

## $LABEL_STATISTICS

| $LABEL_METRIC | $LABEL_VALUE |
|--------|-------|
| $LABEL_TOTAL_PUBLISHERS | $publisher_count |
| $LABEL_INDIVIDUALS | $individual_count |
| $LABEL_ORGANIZATIONS | $organization_count |

## $LABEL_ENTITY_INDEX

| $LABEL_PUBLISHER | $LABEL_TYPE | $LABEL_SOURCES |
|-------|--------|----------|
$entity_index
---

*$LABEL_GENERATED_BY publisher-generator*
EOF

# ============================================================================
# OUTPUT RESULTS
# ============================================================================

readme_created="false"
if [[ -f "$readme_path" ]]; then
  readme_created="true"
fi

if [[ "$json_output" == "true" ]]; then
  cat <<EOF
{
  "success": true,
  "data": {
    "readme_path": "$readme_path",
    "readme_created": $readme_created
  },
  "stats": {
    "publisher_count": $publisher_count,
    "individual_count": $individual_count,
    "organization_count": $organization_count,
    "source_refs_total": $total_source_refs
  }
}
EOF
else
  echo "README created: $readme_path"
  echo "Publishers: $publisher_count (Individuals: $individual_count, Organizations: $organization_count)"
fi

exit 0
