#!/usr/bin/env bash
set -euo pipefail
# generate-claims-readme.sh - Generate README.md for claims directory
#
# Version: 1.0.0
# Purpose: Create provenance chain README with statistics and entity index for verified claims
# Architecture: LLM-Control pattern with JSON I/O, following generate-query-batches-readme.sh pattern
# Compatibility: bash 3.2+ (no associative arrays)
#
# Exit codes:
#   0 - Success
#   2 - Invalid arguments or missing required paths
#   3 - No claim files found


# ============================================================================
# ARGUMENT PARSING
# ============================================================================

project_path=""
json_output="false"
project_language="en"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-path)
      project_path="$2"
      shift 2
      ;;
    --json)
      json_output="true"
      shift
      ;;
    --language)
      project_language="$2"
      shift 2
      ;;
    *)
      echo "{\"success\": false, \"error\": \"Unknown argument: $1\"}" >&2
      exit 2
      ;;
  esac
done

# Validate required arguments
if [[ -z "$project_path" ]]; then
  echo "{\"success\": false, \"error\": \"Required argument: --project-path\"}" >&2
  exit 2
fi

# Validate project path exists
if [[ ! -d "$project_path" ]]; then
  echo "{\"success\": false, \"error\": \"Project path not found: $project_path\"}" >&2
  exit 2
fi

# ============================================================================
# SOURCE CENTRALIZED CONFIG
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Try to source entity-config.sh for DATA_SUBDIR
if [[ -f "${SCRIPT_DIR}/lib/entity-config.sh" ]]; then
  source "${SCRIPT_DIR}/lib/entity-config.sh"
  DATA_SUBDIR="$(get_data_subdir)"
else
  DATA_SUBDIR="data"
fi

# ============================================================================
# LANGUAGE TRANSLATION MAP
# ============================================================================

get_translation() {
  local key="$1"
  case "$project_language" in
    de)
      case "$key" in
        "Verified Claims") echo "Verifizierte Behauptungen" ;;
        "Claims") echo "Behauptungen" ;;
        "Statistics") echo "Statistiken" ;;
        "Mindmap") echo "Mindmap" ;;
        "Entity Index") echo "Entitätsindex" ;;
        "Provenance Chain") echo "Herkunftskette" ;;
        "Generated by") echo "Erstellt von" ;;
        "Metric") echo "Metrik" ;;
        "Value") echo "Wert" ;;
        "Claim") echo "Behauptung" ;;
        "Finding") echo "Erkenntnis" ;;
        "Confidence") echo "Konfidenz" ;;
        "Link") echo "Link" ;;
        "Total Claims") echo "Behauptungen gesamt" ;;
        "Average Confidence") echo "Durchschnittliche Konfidenz" ;;
        "Flagged for Review") echo "Zur Überprüfung markiert" ;;
        "High Confidence") echo "Hohe Konfidenz" ;;
        "Moderate Confidence") echo "Mittlere Konfidenz" ;;
        "Low Confidence") echo "Niedrige Konfidenz" ;;
        "Confidence Distribution") echo "Konfidenzverteilung" ;;
        "Tier") echo "Stufe" ;;
        "Range") echo "Bereich" ;;
        "Count") echo "Anzahl" ;;
        "This directory contains") echo "Dieses Verzeichnis enthält" ;;
        "verified claims extracted from") echo "verifizierte Behauptungen extrahiert aus" ;;
        "research findings") echo "Forschungserkenntnissen" ;;
        *) echo "$key" ;;
      esac
      ;;
    nl)
      case "$key" in
        "Verified Claims") echo "Geverifieerde claims" ;;
        "Claims") echo "Claims" ;;
        "Statistics") echo "Statistieken" ;;
        "Mindmap") echo "Mindmap" ;;
        "Entity Index") echo "Entiteitsindex" ;;
        "Provenance Chain") echo "Herkomst keten" ;;
        "Generated by") echo "Gegenereerd door" ;;
        "Metric") echo "Metriek" ;;
        "Value") echo "Waarde" ;;
        "Claim") echo "Claim" ;;
        "Finding") echo "Bevinding" ;;
        "Confidence") echo "Vertrouwen" ;;
        "Link") echo "Link" ;;
        "Total Claims") echo "Totaal claims" ;;
        "Average Confidence") echo "Gemiddeld vertrouwen" ;;
        "Flagged for Review") echo "Gemarkeerd voor beoordeling" ;;
        "High Confidence") echo "Hoog vertrouwen" ;;
        "Moderate Confidence") echo "Gemiddeld vertrouwen" ;;
        "Low Confidence") echo "Laag vertrouwen" ;;
        "Confidence Distribution") echo "Vertrouwensverdeling" ;;
        "Tier") echo "Niveau" ;;
        "Range") echo "Bereik" ;;
        "Count") echo "Aantal" ;;
        "This directory contains") echo "Deze map bevat" ;;
        "verified claims extracted from") echo "geverifieerde claims geëxtraheerd uit" ;;
        "research findings") echo "onderzoeksbevindingen" ;;
        *) echo "$key" ;;
      esac
      ;;
    fr)
      case "$key" in
        "Verified Claims") echo "Affirmations vérifiées" ;;
        "Claims") echo "Affirmations" ;;
        "Statistics") echo "Statistiques" ;;
        "Mindmap") echo "Carte mentale" ;;
        "Entity Index") echo "Index des entités" ;;
        "Provenance Chain") echo "Chaîne de provenance" ;;
        "Generated by") echo "Généré par" ;;
        "Metric") echo "Métrique" ;;
        "Value") echo "Valeur" ;;
        "Claim") echo "Affirmation" ;;
        "Finding") echo "Résultat" ;;
        "Confidence") echo "Confiance" ;;
        "Link") echo "Lien" ;;
        "Total Claims") echo "Total des affirmations" ;;
        "Average Confidence") echo "Confiance moyenne" ;;
        "Flagged for Review") echo "Signalé pour examen" ;;
        "High Confidence") echo "Confiance élevée" ;;
        "Moderate Confidence") echo "Confiance modérée" ;;
        "Low Confidence") echo "Confiance faible" ;;
        "Confidence Distribution") echo "Distribution de confiance" ;;
        "Tier") echo "Niveau" ;;
        "Range") echo "Plage" ;;
        "Count") echo "Compte" ;;
        "This directory contains") echo "Ce répertoire contient" ;;
        "verified claims extracted from") echo "affirmations vérifiées extraites de" ;;
        "research findings") echo "résultats de recherche" ;;
        *) echo "$key" ;;
      esac
      ;;
    *)  # en default
      echo "$key"
      ;;
  esac
}

# ============================================================================
# PATH CONFIGURATION
# ============================================================================

claims_base_dir="$project_path/10-claims"
claims_dir="$claims_base_dir/$DATA_SUBDIR"
dimensions_dir="$project_path/01-research-dimensions/$DATA_SUBDIR"

# Wikilink script path
if [[ -n "${CLAUDE_PLUGIN_ROOT:-}" ]]; then
  WIKILINK_SCRIPT="${CLAUDE_PLUGIN_ROOT}/scripts/generate-wikilink.sh"
else
  WIKILINK_SCRIPT="${SCRIPT_DIR}/generate-wikilink.sh"
fi

# Validate claims directory exists
if [[ ! -d "$claims_dir" ]]; then
  echo "{\"success\": false, \"error\": \"Claims directory not found: $claims_dir\"}" >&2
  exit 2
fi

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

# Extract YAML frontmatter from markdown file
extract_frontmatter() {
  local file="$1"
  sed -n '/^---$/,/^---$/p' "$file" | sed '1d;$d'
}

# Extract value from YAML frontmatter (simple key: value parsing)
get_frontmatter_value() {
  local file="$1"
  local key="$2"
  local result
  result="$(extract_frontmatter "$file" | grep "^${key}:" | sed "s/^${key}:[[:space:]]*//" | sed 's/^"//' | sed 's/"$//' || true)"
  echo "$result"
}

# Sanitize text for Mermaid mindmap nodes
sanitize_mindmap_label() {
  echo "$1" | sed 's/([^)]*)//g' | sed 's/[:\[\]"<>]//g' | sed 's/  */ /g' | sed 's/^ *//' | sed 's/ *$//'
}

# Generate wikilink using utility script or fallback
generate_wikilink() {
  local entity_dir="$1"
  local filename="$2"
  local display_name="${3:-}"

  local path="${entity_dir}/${DATA_SUBDIR}/${filename}"
  local fallback_link
  if [[ -n "$display_name" ]]; then
    fallback_link="[[$path|$display_name]]"
  else
    fallback_link="[[$path]]"
  fi

  if [[ -x "$WIKILINK_SCRIPT" ]]; then
    local wikilink_result
    if [[ -n "$display_name" ]]; then
      wikilink_result="$(bash "$WIKILINK_SCRIPT" --project-path "$project_path" --entity-dir "$entity_dir" --filename "$filename" --display-name "$display_name" 2>/dev/null || true)"
    else
      wikilink_result="$(bash "$WIKILINK_SCRIPT" --project-path "$project_path" --entity-dir "$entity_dir" --filename "$filename" 2>/dev/null || true)"
    fi

    if [[ -n "$wikilink_result" ]] && echo "$wikilink_result" | jq -e . >/dev/null 2>&1; then
      echo "$wikilink_result" | jq -r '.data.wikilink'
      return
    fi
  fi

  echo "$fallback_link"
}

# ============================================================================
# COLLECT CLAIM FILES
# ============================================================================

claim_files=()
while IFS= read -r -d '' file; do
  claim_files+=("$file")
done < <(find "$claims_dir" -maxdepth 1 -name "claim-*.md" -type f -print0 2>/dev/null | sort -z)

claim_count="${#claim_files[@]}"

if [[ "$claim_count" -eq 0 ]]; then
  echo "{\"success\": false, \"error\": \"No claim files found in $claims_dir\"}" >&2
  exit 3
fi

# ============================================================================
# PARSE CLAIM METADATA (bash 3.2 compatible - no associative arrays)
# ============================================================================

# Track statistics
confidence_sum=0
confidence_count=0
high_confidence_count=0
moderate_confidence_count=0
low_confidence_count=0
flagged_count=0

# Use temp files for dimension grouping (bash 3.2 compatible)
TEMP_DIR="${TMPDIR:-/tmp}/claims-readme-$$"
mkdir -p "$TEMP_DIR"
trap 'rm -rf "$TEMP_DIR"' EXIT

# Track all dimension slugs we've seen
all_dimension_slugs=""

for claim_file in "${claim_files[@]}"; do
  claim_filename="$(basename "$claim_file" .md)"

  # Extract frontmatter values
  claim_text="$(get_frontmatter_value "$claim_file" "claim")"
  if [[ -z "$claim_text" ]]; then
    claim_text="$(get_frontmatter_value "$claim_file" "dc:title")"
  fi
  if [[ -z "$claim_text" ]]; then
    claim_text="$(get_frontmatter_value "$claim_file" "title")"
  fi

  confidence="$(get_frontmatter_value "$claim_file" "confidence")"
  if [[ -z "$confidence" ]]; then
    confidence="$(get_frontmatter_value "$claim_file" "confidence_score")"
  fi

  finding_ref="$(get_frontmatter_value "$claim_file" "finding_ref")"
  if [[ -z "$finding_ref" ]]; then
    finding_ref="$(get_frontmatter_value "$claim_file" "finding_id")"
  fi

  flagged="$(get_frontmatter_value "$claim_file" "flagged_for_review")"
  dimension_ref="$(get_frontmatter_value "$claim_file" "dimension_ref")"

  # Calculate confidence statistics
  if [[ -n "$confidence" ]] && [[ "$confidence" =~ ^[0-9]*\.?[0-9]+$ ]]; then
    # Use bc for floating point arithmetic
    confidence_sum=$(echo "$confidence_sum + $confidence" | bc)
    confidence_count=$((confidence_count + 1))

    # Categorize confidence level
    is_high=$(echo "$confidence > 0.8" | bc)
    is_moderate=$(echo "$confidence >= 0.6" | bc)

    if [[ "$is_high" -eq 1 ]]; then
      high_confidence_count=$((high_confidence_count + 1))
    elif [[ "$is_moderate" -eq 1 ]]; then
      moderate_confidence_count=$((moderate_confidence_count + 1))
    else
      low_confidence_count=$((low_confidence_count + 1))
    fi
  fi

  # Count flagged claims
  if [[ "$flagged" == "true" ]] || [[ "$flagged" == "yes" ]]; then
    flagged_count=$((flagged_count + 1))
  fi

  # Extract dimension slug from reference
  dimension_slug=""
  if [[ -n "$dimension_ref" ]]; then
    dimension_slug="$(echo "$dimension_ref" | grep -o 'dimension-[a-z0-9-]*' | head -1)"
  fi

  if [[ -z "$dimension_slug" ]]; then
    dimension_slug="uncategorized"
  fi

  # Track dimension if new
  if ! echo "$all_dimension_slugs" | grep -q "|${dimension_slug}|"; then
    all_dimension_slugs="${all_dimension_slugs}|${dimension_slug}|"
  fi

  # Fallback claim text if empty
  if [[ -z "$claim_text" ]]; then
    claim_text="$claim_filename"
  fi

  # Append claim data to temp file
  echo "${claim_filename}|${claim_text}|${confidence}|${finding_ref}|${dimension_slug}" >> "$TEMP_DIR/claims_all"
done

# Calculate average confidence
avg_confidence="0.00"
if [[ "$confidence_count" -gt 0 ]]; then
  avg_confidence=$(echo "scale=2; $confidence_sum / $confidence_count" | bc)
fi

# ============================================================================
# BUILD README CONTENT
# ============================================================================

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")"

# Get translated labels
LABEL_VERIFIED_CLAIMS="$(get_translation "Verified Claims")"
LABEL_CLAIMS="$(get_translation "Claims")"
LABEL_STATISTICS="$(get_translation "Statistics")"
LABEL_MINDMAP="$(get_translation "Mindmap")"
LABEL_ENTITY_INDEX="$(get_translation "Entity Index")"
LABEL_PROVENANCE="$(get_translation "Provenance Chain")"
LABEL_GENERATED_BY="$(get_translation "Generated by")"
LABEL_METRIC="$(get_translation "Metric")"
LABEL_VALUE="$(get_translation "Value")"
LABEL_CLAIM="$(get_translation "Claim")"
LABEL_FINDING="$(get_translation "Finding")"
LABEL_CONFIDENCE="$(get_translation "Confidence")"
LABEL_LINK="$(get_translation "Link")"
LABEL_TOTAL_CLAIMS="$(get_translation "Total Claims")"
LABEL_AVG_CONFIDENCE="$(get_translation "Average Confidence")"
LABEL_FLAGGED="$(get_translation "Flagged for Review")"
LABEL_HIGH_CONFIDENCE="$(get_translation "High Confidence")"
LABEL_MODERATE_CONFIDENCE="$(get_translation "Moderate Confidence")"
LABEL_LOW_CONFIDENCE="$(get_translation "Low Confidence")"
LABEL_CONFIDENCE_DIST="$(get_translation "Confidence Distribution")"
LABEL_TIER="$(get_translation "Tier")"
LABEL_RANGE="$(get_translation "Range")"
LABEL_COUNT="$(get_translation "Count")"
LABEL_CONTAINS="$(get_translation "This directory contains")"
LABEL_EXTRACTED="$(get_translation "verified claims extracted from")"
LABEL_RESEARCH_FINDINGS="$(get_translation "research findings")"

# Build Mermaid mindmap by dimension
mindmap_content=""
entity_index=""

# Group claims by dimension
current_dimension=""
while IFS='|' read -r c_filename c_text c_confidence c_finding c_dimension; do
  if [[ -n "$c_filename" ]]; then
    # Add dimension node if new
    if ! [[ "$c_dimension" == "$current_dimension" ]]; then
      dimension_label="$(sanitize_mindmap_label "$c_dimension" | sed 's/^dimension-//' | cut -c1-30)"
      dimension_label="$(echo "$dimension_label" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')"
      mindmap_content+="    $dimension_label"$'\n'
      current_dimension="$c_dimension"
    fi

    # Add claim as child node
    c_text_short="$(sanitize_mindmap_label "$c_text" | cut -c1-35)"
    mindmap_content+="      $c_text_short"$'\n'

    # Generate wikilink for entity index
    claim_wikilink="$(generate_wikilink "10-claims" "$c_filename")"

    # Format confidence for display
    c_confidence_display="${c_confidence:-N/A}"

    entity_index+="| $claim_wikilink | $c_confidence_display |"$'\n'
  fi
done < <(sort -t'|' -k5 "$TEMP_DIR/claims_all" 2>/dev/null || true)

# ============================================================================
# WRITE README FILE
# ============================================================================

readme_path="$claims_base_dir/README.md"

cat > "$readme_path" <<EOF
---
title: "${LABEL_VERIFIED_CLAIMS} Overview"
generated_by: fact-checker
generated_at: $timestamp
claim_count: $claim_count
avg_confidence: $avg_confidence
high_confidence_count: $high_confidence_count
moderate_confidence_count: $moderate_confidence_count
low_confidence_count: $low_confidence_count
flagged_count: $flagged_count
project_language: $project_language
---

# $LABEL_VERIFIED_CLAIMS

$LABEL_CONTAINS $LABEL_EXTRACTED $LABEL_RESEARCH_FINDINGS.

## $LABEL_PROVENANCE

\`\`\`mermaid
mindmap
  root(($LABEL_CLAIMS))
$mindmap_content\`\`\`

## $LABEL_STATISTICS

| $LABEL_METRIC | $LABEL_VALUE |
|--------|-------|
| $LABEL_TOTAL_CLAIMS | $claim_count |
| $LABEL_AVG_CONFIDENCE | $avg_confidence |
| $LABEL_FLAGGED | $flagged_count |

## $LABEL_CONFIDENCE_DIST

| $LABEL_TIER | $LABEL_RANGE | $LABEL_COUNT |
|------|-------|-------|
| $LABEL_HIGH_CONFIDENCE | >0.8 | $high_confidence_count |
| $LABEL_MODERATE_CONFIDENCE | 0.6-0.8 | $moderate_confidence_count |
| $LABEL_LOW_CONFIDENCE | <0.6 | $low_confidence_count |

## $LABEL_ENTITY_INDEX

| $LABEL_CLAIM | $LABEL_CONFIDENCE |
|-------|----------|
$entity_index
---

*$LABEL_GENERATED_BY fact-checker*
EOF

# ============================================================================
# OUTPUT RESULTS
# ============================================================================

readme_created="false"
if [[ -f "$readme_path" ]]; then
  readme_created="true"
fi

if [[ "$json_output" == "true" ]]; then
  cat <<EOF
{
  "success": true,
  "data": {
    "readme_path": "$readme_path",
    "readme_created": $readme_created
  },
  "stats": {
    "claim_count": $claim_count,
    "avg_confidence": $avg_confidence,
    "high_confidence_count": $high_confidence_count,
    "moderate_confidence_count": $moderate_confidence_count,
    "low_confidence_count": $low_confidence_count,
    "flagged_count": $flagged_count
  }
}
EOF
else
  echo "README created: $readme_path"
  echo "Claims: $claim_count, Avg Confidence: $avg_confidence, Flagged: $flagged_count"
fi

exit 0
