#!/usr/bin/env bash
set -euo pipefail
# generate-sources-readme.sh - Generate README.md for sources directory
#
# Version: 1.0.0
# Purpose: Create provenance chain README with statistics and entity index for sources
# Architecture: LLM-Control pattern with JSON I/O, following generate-query-batches-readme.sh pattern
# Compatibility: bash 3.2+ (no associative arrays)
#
# Exit codes:
#   0 - Success
#   2 - Invalid arguments or missing required paths
#   3 - No source files found


# ============================================================================
# ARGUMENT PARSING
# ============================================================================

project_path=""
json_output="false"
project_language="en"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-path)
      project_path="$2"
      shift 2
      ;;
    --json)
      json_output="true"
      shift
      ;;
    --language)
      project_language="$2"
      shift 2
      ;;
    *)
      echo "{\"success\": false, \"error\": \"Unknown argument: $1\"}" >&2
      exit 2
      ;;
  esac
done

# Validate required arguments
if [[ -z "$project_path" ]]; then
  echo "{\"success\": false, \"error\": \"Required argument: --project-path\"}" >&2
  exit 2
fi

# Validate project path exists
if [[ ! -d "$project_path" ]]; then
  echo "{\"success\": false, \"error\": \"Project path not found: $project_path\"}" >&2
  exit 2
fi

# ============================================================================
# SOURCE CENTRALIZED CONFIG
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Try to source entity-config.sh for DATA_SUBDIR
if [[ -f "${SCRIPT_DIR}/lib/entity-config.sh" ]]; then
  source "${SCRIPT_DIR}/lib/entity-config.sh"
  DATA_SUBDIR="$(get_data_subdir)"
else
  DATA_SUBDIR="data"
fi

# ============================================================================
# LANGUAGE TRANSLATION MAP
# ============================================================================

get_translation() {
  local key="$1"
  case "$project_language" in
    de)
      case "$key" in
        "Sources") echo "Quellen" ;;
        "Statistics") echo "Statistiken" ;;
        "Mindmap") echo "Mindmap" ;;
        "Entity Index") echo "Entitätsindex" ;;
        "Provenance Chain") echo "Herkunftskette" ;;
        "Generated by") echo "Erstellt von" ;;
        "Metric") echo "Metrik" ;;
        "Value") echo "Wert" ;;
        "Source") echo "Quelle" ;;
        "Domain") echo "Domäne" ;;
        "Findings") echo "Erkenntnisse" ;;
        "Link") echo "Link" ;;
        "Total Sources") echo "Quellen gesamt" ;;
        "Unique Domains") echo "Einzigartige Domänen" ;;
        "Findings Referenced") echo "Referenzierte Erkenntnisse" ;;
        "This directory contains") echo "Dieses Verzeichnis enthält" ;;
        "research sources extracted from") echo "Forschungsquellen extrahiert aus" ;;
        *) echo "$key" ;;
      esac
      ;;
    nl)
      case "$key" in
        "Sources") echo "Bronnen" ;;
        "Statistics") echo "Statistieken" ;;
        "Mindmap") echo "Mindmap" ;;
        "Entity Index") echo "Entiteitsindex" ;;
        "Provenance Chain") echo "Herkomst keten" ;;
        "Generated by") echo "Gegenereerd door" ;;
        "Metric") echo "Metriek" ;;
        "Value") echo "Waarde" ;;
        "Source") echo "Bron" ;;
        "Domain") echo "Domein" ;;
        "Findings") echo "Bevindingen" ;;
        "Link") echo "Link" ;;
        "Total Sources") echo "Totaal bronnen" ;;
        "Unique Domains") echo "Unieke domeinen" ;;
        "Findings Referenced") echo "Gerefereerde bevindingen" ;;
        "This directory contains") echo "Deze map bevat" ;;
        "research sources extracted from") echo "onderzoeksbronnen geëxtraheerd uit" ;;
        *) echo "$key" ;;
      esac
      ;;
    fr)
      case "$key" in
        "Sources") echo "Sources" ;;
        "Statistics") echo "Statistiques" ;;
        "Mindmap") echo "Carte mentale" ;;
        "Entity Index") echo "Index des entités" ;;
        "Provenance Chain") echo "Chaîne de provenance" ;;
        "Generated by") echo "Généré par" ;;
        "Metric") echo "Métrique" ;;
        "Value") echo "Valeur" ;;
        "Source") echo "Source" ;;
        "Domain") echo "Domaine" ;;
        "Findings") echo "Résultats" ;;
        "Link") echo "Lien" ;;
        "Total Sources") echo "Total des sources" ;;
        "Unique Domains") echo "Domaines uniques" ;;
        "Findings Referenced") echo "Résultats référencés" ;;
        "This directory contains") echo "Ce répertoire contient" ;;
        "research sources extracted from") echo "sources de recherche extraites de" ;;
        *) echo "$key" ;;
      esac
      ;;
    *)  # en default
      echo "$key"
      ;;
  esac
}

# ============================================================================
# PATH CONFIGURATION
# ============================================================================

sources_base_dir="$project_path/07-sources"
sources_dir="$sources_base_dir/$DATA_SUBDIR"
findings_dir="$project_path/04-findings/$DATA_SUBDIR"

# Wikilink script path
if [[ -n "${CLAUDE_PLUGIN_ROOT:-}" ]]; then
  WIKILINK_SCRIPT="${CLAUDE_PLUGIN_ROOT}/scripts/generate-wikilink.sh"
else
  WIKILINK_SCRIPT="${SCRIPT_DIR}/generate-wikilink.sh"
fi

# Validate sources directory exists
if [[ ! -d "$sources_dir" ]]; then
  echo "{\"success\": false, \"error\": \"Sources directory not found: $sources_dir\"}" >&2
  exit 2
fi

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

# Extract YAML frontmatter from markdown file
extract_frontmatter() {
  local file="$1"
  sed -n '/^---$/,/^---$/p' "$file" | sed '1d;$d'
}

# Extract value from YAML frontmatter (simple key: value parsing)
get_frontmatter_value() {
  local file="$1"
  local key="$2"
  local result
  result="$(extract_frontmatter "$file" | grep "^${key}:" | sed "s/^${key}:[[:space:]]*//" | sed 's/^"//' | sed 's/"$//' || true)"
  echo "$result"
}

# Sanitize text for Mermaid mindmap nodes
sanitize_mindmap_label() {
  echo "$1" | sed 's/([^)]*)//g' | sed 's/[:\[\]"<>]//g' | sed 's/  */ /g' | sed 's/^ *//' | sed 's/ *$//'
}

# Extract domain from URL
extract_domain() {
  local url="$1"
  echo "$url" | sed -E 's|^https?://||' | sed -E 's|/.*||' | sed 's/^www\.//'
}

# Generate wikilink using utility script or fallback
generate_wikilink() {
  local entity_dir="$1"
  local filename="$2"
  local display_name="${3:-}"

  local path="${entity_dir}/${DATA_SUBDIR}/${filename}"
  local fallback_link
  if [[ -n "$display_name" ]]; then
    fallback_link="[[$path|$display_name]]"
  else
    fallback_link="[[$path]]"
  fi

  if [[ -x "$WIKILINK_SCRIPT" ]]; then
    local wikilink_result
    if [[ -n "$display_name" ]]; then
      wikilink_result="$(bash "$WIKILINK_SCRIPT" --project-path "$project_path" --entity-dir "$entity_dir" --filename "$filename" --display-name "$display_name" 2>/dev/null || true)"
    else
      wikilink_result="$(bash "$WIKILINK_SCRIPT" --project-path "$project_path" --entity-dir "$entity_dir" --filename "$filename" 2>/dev/null || true)"
    fi

    if [[ -n "$wikilink_result" ]] && echo "$wikilink_result" | jq -e . >/dev/null 2>&1; then
      echo "$wikilink_result" | jq -r '.data.wikilink'
      return
    fi
  fi

  echo "$fallback_link"
}

# ============================================================================
# COLLECT SOURCE FILES
# ============================================================================

source_files=()
while IFS= read -r -d '' file; do
  source_files+=("$file")
done < <(find "$sources_dir" -maxdepth 1 -name "source-*.md" -type f -print0 2>/dev/null | sort -z)

source_count="${#source_files[@]}"

if [[ "$source_count" -eq 0 ]]; then
  echo "{\"success\": false, \"error\": \"No source files found in $sources_dir\"}" >&2
  exit 3
fi

# ============================================================================
# PARSE SOURCE METADATA (bash 3.2 compatible - no associative arrays)
# ============================================================================

# Track statistics
total_finding_refs=0
unique_domains=""
domain_count=0

# Use temp files for domain grouping (bash 3.2 compatible)
TEMP_DIR="${TMPDIR:-/tmp}/sources-readme-$$"
mkdir -p "$TEMP_DIR"
trap 'rm -rf "$TEMP_DIR"' EXIT

for source_file in "${source_files[@]}"; do
  source_filename="$(basename "$source_file" .md)"

  # Extract frontmatter values
  source_url="$(get_frontmatter_value "$source_file" "url")"
  source_title="$(get_frontmatter_value "$source_file" "dc:title")"
  if [[ -z "$source_title" ]]; then
    source_title="$(get_frontmatter_value "$source_file" "title")"
  fi

  # Count finding references (finding_ids array)
  finding_ids="$(get_frontmatter_value "$source_file" "finding_ids")"
  if [[ -n "$finding_ids" ]]; then
    # Count items in YAML array format [item1, item2, ...]
    finding_count="$(echo "$finding_ids" | tr ',' '\n' | grep -c '[a-z]' || echo "0")"
    total_finding_refs=$((total_finding_refs + finding_count))
  else
    finding_count=0
  fi

  # Extract domain from URL
  domain=""
  if [[ -n "$source_url" ]]; then
    domain="$(extract_domain "$source_url")"
  fi

  if [[ -z "$domain" ]]; then
    domain="unknown"
  fi

  # Track domain if new
  if ! echo "$unique_domains" | grep -q "|${domain}|"; then
    unique_domains="${unique_domains}|${domain}|"
    domain_count=$((domain_count + 1))
    # Store domain title in temp file
    echo "$domain" > "$TEMP_DIR/domain_${domain_count}"
  fi

  # Fallback title if empty
  if [[ -z "$source_title" ]]; then
    source_title="$source_filename"
  fi

  # Append source data to domain's temp file
  echo "${source_filename}|${source_title}|${domain}|${finding_count}" >> "$TEMP_DIR/sources_all"
done

# ============================================================================
# BUILD README CONTENT
# ============================================================================

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")"

# Get translated labels
LABEL_SOURCES="$(get_translation "Sources")"
LABEL_STATISTICS="$(get_translation "Statistics")"
LABEL_MINDMAP="$(get_translation "Mindmap")"
LABEL_ENTITY_INDEX="$(get_translation "Entity Index")"
LABEL_PROVENANCE="$(get_translation "Provenance Chain")"
LABEL_GENERATED_BY="$(get_translation "Generated by")"
LABEL_METRIC="$(get_translation "Metric")"
LABEL_VALUE="$(get_translation "Value")"
LABEL_SOURCE="$(get_translation "Source")"
LABEL_DOMAIN="$(get_translation "Domain")"
LABEL_FINDINGS="$(get_translation "Findings")"
LABEL_LINK="$(get_translation "Link")"
LABEL_TOTAL_SOURCES="$(get_translation "Total Sources")"
LABEL_UNIQUE_DOMAINS="$(get_translation "Unique Domains")"
LABEL_FINDINGS_REFERENCED="$(get_translation "Findings Referenced")"
LABEL_CONTAINS="$(get_translation "This directory contains")"
LABEL_EXTRACTED="$(get_translation "research sources extracted from")"

# Build Mermaid mindmap by domain
mindmap_content=""
entity_index=""

# Group sources by domain
current_domain=""
while IFS='|' read -r s_filename s_title s_domain s_findings; do
  if [[ -n "$s_filename" ]]; then
    # Add domain node if new
    if ! [[ "$s_domain" == "$current_domain" ]]; then
      domain_label="$(sanitize_mindmap_label "$s_domain" | cut -c1-30)"
      mindmap_content+="    $domain_label"$'\n'
      current_domain="$s_domain"
    fi

    # Add source as child node
    s_title_short="$(sanitize_mindmap_label "$s_title" | cut -c1-35)"
    mindmap_content+="      $s_title_short"$'\n'

    # Generate wikilink for entity index
    source_wikilink="$(generate_wikilink "07-sources" "$s_filename" "$s_title")"
    entity_index+="| $source_wikilink | $s_domain | $s_findings |"$'\n'
  fi
done < <(sort -t'|' -k3 "$TEMP_DIR/sources_all" 2>/dev/null || true)

# ============================================================================
# WRITE README FILE
# ============================================================================

readme_path="$sources_base_dir/README.md"

cat > "$readme_path" <<EOF
---
title: "${LABEL_SOURCES} Overview"
generated_by: source-creator
generated_at: $timestamp
source_count: $source_count
domain_count: $domain_count
finding_refs_total: $total_finding_refs
project_language: $project_language
---

# $LABEL_SOURCES

$LABEL_CONTAINS $LABEL_EXTRACTED research findings.

## $LABEL_PROVENANCE

\`\`\`mermaid
mindmap
  root(($LABEL_SOURCES))
$mindmap_content\`\`\`

## $LABEL_STATISTICS

| $LABEL_METRIC | $LABEL_VALUE |
|--------|-------|
| $LABEL_TOTAL_SOURCES | $source_count |
| $LABEL_UNIQUE_DOMAINS | $domain_count |
| $LABEL_FINDINGS_REFERENCED | $total_finding_refs |

## $LABEL_ENTITY_INDEX

| $LABEL_SOURCE | $LABEL_DOMAIN | $LABEL_FINDINGS |
|-------|--------|----------|
$entity_index
---

*$LABEL_GENERATED_BY source-creator*
EOF

# ============================================================================
# OUTPUT RESULTS
# ============================================================================

readme_created="false"
if [[ -f "$readme_path" ]]; then
  readme_created="true"
fi

if [[ "$json_output" == "true" ]]; then
  cat <<EOF
{
  "success": true,
  "data": {
    "readme_path": "$readme_path",
    "readme_created": $readme_created
  },
  "stats": {
    "source_count": $source_count,
    "domain_count": $domain_count,
    "finding_refs_total": $total_finding_refs
  }
}
EOF
else
  echo "README created: $readme_path"
  echo "Sources: $source_count, Domains: $domain_count"
fi

exit 0
