#!/usr/bin/env bash
set -euo pipefail
# generate-query-batches-readme.sh - Generate README.md for query batches directory
#
# Version: 1.3.0
# Purpose: Create provenance chain README with statistics and entity index for query batches
# Changelog:
# - v1.3.0: Use shortest unique path format for wikilinks (Obsidian default)
# - v1.2.0: Fix wikilink script path, remove workspace prefix from fallback (match generate-wikilink.sh v1.4.0)
# - v1.1.0: Fix wikilink fallbacks for multi-project workspaces
# Architecture: LLM-Control pattern with JSON I/O, following dimension-planner pattern
# Compatibility: bash 3.2+ (no associative arrays)
#
# Exit codes:
#   0 - Success
#   2 - Invalid arguments or missing required paths
#   3 - No batch files found


# ============================================================================
# ARGUMENT PARSING
# ============================================================================

project_path=""
json_output="false"
project_language="en"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-path)
      project_path="$2"
      shift 2
      ;;
    --json)
      json_output="true"
      shift
      ;;
    --language)
      project_language="$2"
      shift 2
      ;;
    *)
      echo "{\"success\": false, \"error\": \"Unknown argument: $1\"}" >&2
      exit 2
      ;;
  esac
done

# Validate required arguments
if [[ -z "$project_path" ]]; then
  echo "{\"success\": false, \"error\": \"Required argument: --project-path\"}" >&2
  exit 2
fi

# Validate project path exists
if [[ ! -d "$project_path" ]]; then
  echo "{\"success\": false, \"error\": \"Project path not found: $project_path\"}" >&2
  exit 2
fi

# ============================================================================
# SOURCE CENTRALIZED CONFIG
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Try to source entity-config.sh for DATA_SUBDIR
if [[ -f "${SCRIPT_DIR}/../../../scripts/lib/entity-config.sh" ]]; then
  source "${SCRIPT_DIR}/../../../scripts/lib/entity-config.sh"
  DATA_SUBDIR="$(get_data_subdir)"
else
  DATA_SUBDIR="data"
fi

# ============================================================================
# LANGUAGE TRANSLATION MAP
# ============================================================================

get_translation() {
  local key="$1"
  case "$project_language" in
    de)
      case "$key" in
        "Query Batches Overview") echo "Suchanfragen-Übersicht" ;;
        "Query Batches") echo "Suchanfragen" ;;
        "Provenance Chain") echo "Herkunftskette" ;;
        "Statistics") echo "Statistiken" ;;
        "Entity Index") echo "Entitätsindex" ;;
        "Metric") echo "Metrik" ;;
        "Value") echo "Wert" ;;
        "Batch") echo "Batch" ;;
        "Question") echo "Frage" ;;
        "Queries") echo "Suchanfragen" ;;
        "Generated by") echo "Erstellt von" ;;
        "Initial Question") echo "Ausgangsfrage" ;;
        "Total Batches") echo "Batches gesamt" ;;
        "Total Queries") echo "Suchanfragen gesamt" ;;
        "Avg Queries/Batch") echo "Ø Suchanfragen/Batch" ;;
        "Hierarchical view of query batches organized by research dimension and refined question.") echo "Hierarchische Ansicht der Suchanfragen, organisiert nach Forschungsdimension und verfeinerter Frage." ;;
        *) echo "$key" ;;
      esac
      ;;
    nl)
      case "$key" in
        "Query Batches Overview") echo "Zoekopdrachten Overzicht" ;;
        "Query Batches") echo "Zoekopdrachten" ;;
        "Provenance Chain") echo "Herkomst keten" ;;
        "Statistics") echo "Statistieken" ;;
        "Entity Index") echo "Entiteitsindex" ;;
        "Metric") echo "Metriek" ;;
        "Value") echo "Waarde" ;;
        "Batch") echo "Batch" ;;
        "Question") echo "Vraag" ;;
        "Queries") echo "Zoekopdrachten" ;;
        "Generated by") echo "Gegenereerd door" ;;
        "Initial Question") echo "Initiële vraag" ;;
        "Total Batches") echo "Totaal batches" ;;
        "Total Queries") echo "Totaal zoekopdrachten" ;;
        "Avg Queries/Batch") echo "Gem. zoekopdrachten/batch" ;;
        "Hierarchical view of query batches organized by research dimension and refined question.") echo "Hiërarchische weergave van zoekopdrachten georganiseerd per onderzoeksdimensie en verfijnde vraag." ;;
        *) echo "$key" ;;
      esac
      ;;
    fr)
      case "$key" in
        "Query Batches Overview") echo "Aperçu des lots de requêtes" ;;
        "Query Batches") echo "Lots de requêtes" ;;
        "Provenance Chain") echo "Chaîne de provenance" ;;
        "Statistics") echo "Statistiques" ;;
        "Entity Index") echo "Index des entités" ;;
        "Metric") echo "Métrique" ;;
        "Value") echo "Valeur" ;;
        "Batch") echo "Lot" ;;
        "Question") echo "Question" ;;
        "Queries") echo "Requêtes" ;;
        "Generated by") echo "Généré par" ;;
        "Initial Question") echo "Question initiale" ;;
        "Total Batches") echo "Total des lots" ;;
        "Total Queries") echo "Total des requêtes" ;;
        "Avg Queries/Batch") echo "Moy. requêtes/lot" ;;
        "Hierarchical view of query batches organized by research dimension and refined question.") echo "Vue hiérarchique des lots de requêtes organisés par dimension de recherche et question affinée." ;;
        *) echo "$key" ;;
      esac
      ;;
    *)  # en default
      echo "$key"
      ;;
  esac
}

# ============================================================================
# PATH CONFIGURATION
# ============================================================================

batches_base_dir="$project_path/03-query-batches"
batches_dir="$batches_base_dir/$DATA_SUBDIR"
questions_dir="$project_path/02-refined-questions/$DATA_SUBDIR"
dimensions_dir="$project_path/01-research-dimensions/$DATA_SUBDIR"
initial_question_dir="$project_path/00-initial-question/$DATA_SUBDIR"


# Validate batches directory exists
if [[ ! -d "$batches_dir" ]]; then
  echo "{\"success\": false, \"error\": \"Query batches directory not found: $batches_dir\"}" >&2
  exit 2
fi

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

# Extract YAML frontmatter from markdown file
# Usage: extract_frontmatter <file_path>
extract_frontmatter() {
  local file="$1"
  sed -n '/^---$/,/^---$/p' "$file" | sed '1d;$d'
}

# Extract value from YAML frontmatter (simple key: value parsing)
# Usage: get_frontmatter_value <file_path> <key>
# Returns empty string if key not found (doesn't fail)
get_frontmatter_value() {
  local file="$1"
  local key="$2"
  local result
  result="$(extract_frontmatter "$file" | grep "^${key}:" | sed "s/^${key}:[[:space:]]*//" | sed 's/^"//' | sed 's/"$//' || true)"
  echo "$result"
}

# Sanitize text for Mermaid mindmap nodes
# Removes parentheses and special chars to prevent parsing errors
sanitize_mindmap_label() {
  echo "$1" | sed 's/([^)]*)//g' | sed 's/[:\[\]"]//g' | sed 's/  */ /g' | sed 's/^ *//' | sed 's/ *$//'
}

# Generate wikilink using shortest unique path format (Obsidian default)
# Fix v1.3.0: Use filename-only format for Obsidian compatibility
generate_wikilink() {
  local filename="$1"
  local display_name="${2:-}"

  # Use shortest unique path format (filename only, no directory path)
  if [[ -n "$display_name" ]]; then
    echo "[[$filename|$display_name]]"
  else
    echo "[[$filename]]"
  fi
}

# ============================================================================
# COLLECT BATCH FILES
# ============================================================================

batch_files=()
while IFS= read -r -d '' file; do
  batch_files+=("$file")
done < <(find "$batches_dir" -maxdepth 1 -name "*.md" -type f -print0 2>/dev/null | sort -z)

batch_count="${#batch_files[@]}"

if [[ "$batch_count" -eq 0 ]]; then
  echo "{\"success\": false, \"error\": \"No batch files found in $batches_dir\"}" >&2
  exit 3
fi

# ============================================================================
# PARSE BATCH METADATA (bash 3.2 compatible - no associative arrays)
# ============================================================================

# Track statistics
total_queries=0
dimension_count=0

# Use temp files for dimension grouping (bash 3.2 compatible)
TEMP_DIR="${TMPDIR:-/tmp}/batch-readme-$$"
mkdir -p "$TEMP_DIR"
trap 'rm -rf "$TEMP_DIR"' EXIT

# Track all dimension IDs we've seen
all_dimension_ids=""

for batch_file in "${batch_files[@]}"; do
  batch_filename="$(basename "$batch_file" .md)"

  # Extract frontmatter values (handle multiple key name formats)
  # Try 'question_id' first, then 'refined_question_id', then derive from batch_id
  question_id="$(get_frontmatter_value "$batch_file" "question_id")"
  if [[ -z "$question_id" ]]; then
    question_id="$(get_frontmatter_value "$batch_file" "refined_question_id")"
  fi
  if [[ -z "$question_id" ]]; then
    # Derive from batch_id by removing '-batch' suffix
    batch_id_val="$(get_frontmatter_value "$batch_file" "batch_id")"
    if [[ -n "$batch_id_val" ]] && [[ "$batch_id_val" == *-batch ]]; then
      question_id="${batch_id_val%-batch}"
    fi
  fi

  # Try 'queries_count' first, then 'queries_total', then 'config_count'
  queries_count="$(get_frontmatter_value "$batch_file" "queries_count")"
  if [[ -z "$queries_count" ]]; then
    queries_count="$(get_frontmatter_value "$batch_file" "queries_total")"
  fi
  if [[ -z "$queries_count" ]]; then
    queries_count="$(get_frontmatter_value "$batch_file" "config_count")"
  fi

  # Default queries_count to 0 if not found or not a number
  if [[ -z "$queries_count" ]] || ! [[ "$queries_count" =~ ^[0-9]+$ ]]; then
    queries_count=0
  fi

  total_queries=$((total_queries + queries_count))

  # Extract batch title from markdown header (handle "# Query Batch:" or "# Query Batch")
  batch_title="$(grep "^# Query Batch" "$batch_file" 2>/dev/null | sed 's/^# Query Batch:[[:space:]]*//' | sed 's/^# Query Batch$//' | head -1 || true)"
  if [[ -z "$batch_title" ]]; then
    # Use question_id slug as fallback title
    if [[ -n "$question_id" ]]; then
      batch_title="$(echo "$question_id" | sed 's/^question-//' | sed 's/-[a-z0-9]\{8\}$//' | tr '-' ' ')"
    else
      batch_title="$batch_filename"
    fi
  fi

  # Look up question file to get dimension reference
  dimension_id=""
  dimension_title=""

  if [[ -n "$question_id" ]] && [[ -d "$questions_dir" ]]; then
    question_file="$(find "$questions_dir" -name "${question_id}.md" -type f 2>/dev/null | head -1)"

    if [[ -n "$question_file" ]] && [[ -f "$question_file" ]]; then
      # Extract dimension_ref from question frontmatter
      dimension_ref="$(get_frontmatter_value "$question_file" "dimension_ref")"

      # Parse dimension ID from wikilink: [[path/to/dimension-slug-hash]]
      if [[ -n "$dimension_ref" ]]; then
        dimension_id="$(echo "$dimension_ref" | grep -o 'dimension-[a-z0-9-]*' | head -1)"

        # Look up dimension file for title
        if [[ -n "$dimension_id" ]] && [[ -d "$dimensions_dir" ]]; then
          dimension_file="$(find "$dimensions_dir" -name "${dimension_id}.md" -type f 2>/dev/null | head -1)"

          if [[ -n "$dimension_file" ]] && [[ -f "$dimension_file" ]]; then
            dimension_title="$(grep "^# " "$dimension_file" 2>/dev/null | sed 's/^# //' | head -1)"
          fi
        fi
      fi
    fi
  fi

  # Default dimension if not found
  if [[ -z "$dimension_id" ]]; then
    dimension_id="unknown"
    dimension_title="Unknown Dimension"
  fi

  # Store dimension title in temp file
  echo "$dimension_title" > "$TEMP_DIR/dim_title_${dimension_id}"

  # Track dimension ID if new
  if ! echo "$all_dimension_ids" | grep -q "|${dimension_id}|"; then
    all_dimension_ids="${all_dimension_ids}|${dimension_id}|"
    dimension_count=$((dimension_count + 1))
  fi

  # Append batch data to dimension's temp file
  echo "${batch_filename}|${batch_title}|${queries_count}|${question_id}" >> "$TEMP_DIR/dim_batches_${dimension_id}"
done

# ============================================================================
# GET INITIAL QUESTION REFERENCE
# ============================================================================

initial_question_id=""
initial_question_title=""

if [[ -d "$initial_question_dir" ]]; then
  initial_question_file="$(find "$initial_question_dir" -name "question-*.md" -type f 2>/dev/null | head -1)"

  if [[ -n "$initial_question_file" ]]; then
    initial_question_id="$(basename "$initial_question_file" .md)"
    initial_question_title="$(echo "$initial_question_id" | sed 's/^question-//' | sed 's/-[a-z0-9]\{8\}$//' | tr '-' ' ' | cut -c1-40)"
    # Capitalize first letter of each word
    initial_question_title="$(echo "$initial_question_title" | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')"
  fi
fi

if [[ -z "$initial_question_id" ]]; then
  initial_question_id="initial-question"
  initial_question_title="Research Question"
fi

# Generate initial question wikilink
INITIAL_QUESTION_WIKILINK="$(generate_wikilink "$initial_question_id")"

# ============================================================================
# BUILD README CONTENT
# ============================================================================

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")"

# Calculate average
if [[ "$batch_count" -gt 0 ]]; then
  avg_queries="$(echo "scale=1; $total_queries / $batch_count" | bc)"
else
  avg_queries="0.0"
fi

# Build Mermaid mindmap by reading temp files
mindmap_content=""
entity_index=""

# Process each dimension
for dim_title_file in "$TEMP_DIR"/dim_title_*; do
  if [[ -f "$dim_title_file" ]]; then
    dim_id="$(basename "$dim_title_file" | sed 's/^dim_title_//')"
    dim_title="$(cat "$dim_title_file")"
    dim_title_short="$(sanitize_mindmap_label "$dim_title" | cut -c1-35)"
    mindmap_content+="    $dim_title_short"$'\n'

    # Read batches for this dimension
    batches_file="$TEMP_DIR/dim_batches_${dim_id}"
    if [[ -f "$batches_file" ]]; then
      # Get queries label for mindmap (lowercase for readability)
      queries_label="$(get_translation "Queries" | tr '[:upper:]' '[:lower:]')"
      while IFS='|' read -r b_filename b_title b_queries b_question_id; do
        if [[ -n "$b_filename" ]]; then
          b_title_short="$(sanitize_mindmap_label "$b_title" | cut -c1-30)"
          mindmap_content+="      $b_title_short ($b_queries $queries_label)"$'\n'

          # Generate wikilinks for entity index (no display names - pipes break table parsing)
          batch_wikilink="$(generate_wikilink "$b_filename")"

          question_wikilink=""
          if [[ -n "$b_question_id" ]]; then
            question_wikilink="$(generate_wikilink "$b_question_id")"
          else
            question_wikilink="(no question ref)"
          fi

          entity_index+="| $batch_wikilink | $question_wikilink | $b_queries |"$'\n'
        fi
      done < "$batches_file"
    fi
  fi
done

# ============================================================================
# WRITE README FILE
# ============================================================================

readme_path="$batches_base_dir/README.md"

# Get translated labels
t_title="$(get_translation "Query Batches Overview")"
t_query_batches="$(get_translation "Query Batches")"
t_description="$(get_translation "Hierarchical view of query batches organized by research dimension and refined question.")"
t_provenance="$(get_translation "Provenance Chain")"
t_statistics="$(get_translation "Statistics")"
t_metric="$(get_translation "Metric")"
t_value="$(get_translation "Value")"
t_initial_question="$(get_translation "Initial Question")"
t_total_batches="$(get_translation "Total Batches")"
t_total_queries="$(get_translation "Total Queries")"
t_avg_queries="$(get_translation "Avg Queries/Batch")"
t_entity_index="$(get_translation "Entity Index")"
t_batch="$(get_translation "Batch")"
t_question="$(get_translation "Question")"
t_queries="$(get_translation "Queries")"
t_generated_by="$(get_translation "Generated by")"

cat > "$readme_path" <<EOF
---
title: "$t_title"
generated_by: batch-creator
generated_at: $timestamp
initial_question: "$initial_question_id"
batch_count: $batch_count
total_queries: $total_queries
---

# $t_query_batches

$t_description

## $t_provenance

\`\`\`mermaid
mindmap
  root(($initial_question_title))
$mindmap_content\`\`\`

## $t_statistics

| $t_metric | $t_value |
|--------|-------|
| $t_initial_question | $INITIAL_QUESTION_WIKILINK |
| $t_total_batches | $batch_count |
| $t_total_queries | $total_queries |
| $t_avg_queries | $avg_queries |

## $t_entity_index

| $t_batch | $t_question | $t_queries |
|-------|----------|---------|
$entity_index
---

*$t_generated_by batch-creator Phase 4*
EOF

# ============================================================================
# OUTPUT RESULTS
# ============================================================================

readme_created="false"
if [[ -f "$readme_path" ]]; then
  readme_created="true"
fi

if [[ "$json_output" == "true" ]]; then
  cat <<EOF
{
  "success": true,
  "data": {
    "readme_path": "$readme_path",
    "readme_created": $readme_created
  },
  "stats": {
    "batch_count": $batch_count,
    "total_queries": $total_queries,
    "avg_queries_per_batch": $avg_queries,
    "dimension_count": $dimension_count
  }
}
EOF
else
  echo "README created: $readme_path"
  echo "Batches: $batch_count, Total queries: $total_queries"
fi

exit 0
