#!/usr/bin/env python3
"""Generate the human-browsable assumptions.md register at a cogni-consult
engagement root.

Reads the engagement-root assumptions.json registry (the single source of truth
for {{asm:id}} values — see references/data-model.md) fail-soft, exactly the way
generate-engagement-readme.py's load_assumptions does, and writes
<engagement-dir>/assumptions.md with:

  1. A summary table — one row per assumption: id (linking to its in-page
     `## <slug>` anchor), value, provenance type, status, source host, and
     used_by[] count — the glanceable "all my assumptions and where they stand"
     view.
  2. One anchored `## <slug>` section per assumption below the table, carrying
     value, provenance type/status, rationale, the citation source-lineage quad
     (source_url, entity_ref, propagated_at, claim_id), and used_by[] backlinks.

The `## <slug>` heading is the entry id minus its `asm-` prefix, so it is the
exact Obsidian anchor the resolver's `--mode link` output points at
(`[[assumptions#<slug>|<value>]]`).

One file, not a directory of per-assumption pages. Read-only over all engagement
state except the assumptions.md it writes. Like generate-engagement-readme.py it
refuses to overwrite a hand-authored assumptions.md (one lacking the generated
marker footer).

Usage: python3 register-generator.py <engagement-dir>
Output: JSON {"success": bool, "data": {...}, "error": "string"}. Stdlib-only.
"""

import argparse
import json
import os
import sys
import urllib.parse


# Footer sentinel identifying a script-generated register. The overwrite guard in
# main() keys on it: an assumptions.md without this marker is hand-authored and is
# never overwritten. Kept in sync with the stub engagement-init.sh scaffolds.
GENERATED_MARKER = (
    "_Auto-generated assumption register — regenerated by register-generator.py; "
    "edits here are overwritten._"
)


def load_assumptions(engagement_dir):
    """Read the engagement-root assumptions.json registry fail-soft, mirroring
    generate-engagement-readme.py: a missing / empty / unreadable / malformed
    registry degrades to an empty list, never an error."""
    path = os.path.join(engagement_dir, "assumptions.json")
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError, OSError, UnicodeError):
        return []
    entries = data.get("assumptions") if isinstance(data, dict) else None
    if not isinstance(entries, list):
        return []
    # Drop non-dict elements so a hand-corrupted registry degrades to the usable
    # records rather than raising downstream — matching the fail-soft contract.
    return [e for e in entries if isinstance(e, dict)]


def _md_cell(s):
    """Escape a value for a markdown table cell (pipes split columns; newlines
    break the row)."""
    return str(s if s is not None else "").replace("|", "\\|").replace("\n", " ")


def _slug(entry):
    """The `## <slug>` anchor for an entry: its id minus the `asm-` prefix, or
    the raw id when it does not carry the prefix (defensive — the resolver only
    emits links for prefixed ids)."""
    asm_id = str(entry.get("id") or "")
    return asm_id[4:] if asm_id.startswith("asm-") else asm_id


def _source_host(entry):
    """A compact source label for the summary table: the citation source_url's
    host, or '—' when there is no citation."""
    citation = entry.get("citation")
    if not isinstance(citation, dict):
        return "—"
    url = citation.get("source_url")
    if not isinstance(url, str) or not url:
        return "—"
    host = urllib.parse.urlparse(url).netloc
    return host or url


def _used_by(entry):
    """The used_by[] edge list as a list of dicts, fail-soft to []."""
    ub = entry.get("used_by")
    return [r for r in ub if isinstance(r, dict)] if isinstance(ub, list) else []


def render_register(assumptions):
    lines = ["# Assumptions", ""]
    if not assumptions:
        lines += ["No assumptions registered yet.", ""]
        lines += ["---", "", GENERATED_MARKER, ""]
        return "\n".join(lines)

    n = len(assumptions)
    plural = "assumption" if n == 1 else "assumptions"
    lines.append("%d %s registered." % (n, plural))

    # Summary table — the glanceable overview. The id links to its in-page anchor.
    lines += ["", "| ID | Value | Type | Status | Source | Used by |",
              "|---|---|---|---|---|---|"]
    for a in assumptions:
        slug = _slug(a)
        id_cell = "[%s](#%s)" % (_md_cell(slug), slug) if slug else "—"
        lines.append(
            "| %s | %s | %s | %s | %s | %d |" % (
                id_cell,
                _md_cell(a.get("value")),
                _md_cell(a.get("provenance_type") or "—"),
                _md_cell(a.get("status") or "—"),
                _md_cell(_source_host(a)),
                len(_used_by(a)),
            )
        )

    # Anchored per-assumption sections — the click-through detail.
    for a in assumptions:
        slug = _slug(a)
        lines += ["", "## %s" % slug, ""]
        name = a.get("name")
        if name:
            lines.append("**%s**" % name)
            lines.append("")
        lines.append("- **Value:** %s" % (a.get("value") if a.get("value") is not None else "—"))
        ptype = a.get("provenance_type")
        status = a.get("status")
        if ptype or status:
            lines.append("- **Provenance:** %s / %s" % (ptype or "—", status or "—"))
        rationale = a.get("rationale")
        if rationale:
            lines.append("- **Rationale:** %s" % rationale)
        citation = a.get("citation")
        if isinstance(citation, dict) and any(citation.get(k) for k in
                                              ("source_url", "entity_ref", "propagated_at", "claim_id")):
            parts = []
            url = citation.get("source_url")
            if url:
                parts.append("[%s](%s)" % (_source_host(a), url))
            if citation.get("entity_ref"):
                parts.append("entity_ref `%s`" % citation["entity_ref"])
            if citation.get("propagated_at"):
                parts.append("propagated %s" % citation["propagated_at"])
            if citation.get("claim_id"):
                parts.append("claim `%s`" % citation["claim_id"])
            lines.append("- **Source:** %s" % " · ".join(parts))
        used_by = _used_by(a)
        if used_by:
            rendered = ", ".join(
                "`%s`%s" % (
                    r.get("file", "?"),
                    " (resolved %s)" % r["resolved_at"] if r.get("resolved_at") else "",
                )
                for r in used_by
            )
            lines.append("- **Used by:** %s" % rendered)
        else:
            lines.append("- **Used by:** _(not yet cited)_")

    lines += ["", "---", "", GENERATED_MARKER, ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate the browsable assumptions.md register from assumptions.json")
    parser.add_argument("engagement_dir", help="engagement root (directory holding assumptions.json)")
    args = parser.parse_args()

    register_path = os.path.join(args.engagement_dir, "assumptions.md")
    try:
        assumptions = load_assumptions(args.engagement_dir)
        register = render_register(assumptions)
        # Never clobber a hand-authored register: an existing assumptions.md
        # without the generated-marker footer was written by a person.
        if os.path.exists(register_path):
            with open(register_path, encoding="utf-8") as f:
                existing = f.read()
            if GENERATED_MARKER not in existing:
                print(json.dumps({
                    "success": False,
                    "data": {"register_path": register_path},
                    "error": "existing assumptions.md was not generated by this script "
                             "(marker absent); refusing to overwrite a hand-authored register",
                }))
                return 1
        with open(register_path, "w", encoding="utf-8") as f:
            f.write(register)
    except (OSError, UnicodeError, TypeError, AttributeError) as exc:
        print(json.dumps({"success": False, "data": {}, "error": "register generation failed: %s" % exc}))
        return 1

    print(json.dumps({
        "success": True,
        "data": {
            "register_path": register_path,
            "assumptions_count": len(assumptions),
        },
        "error": "",
    }))
    return 0


if __name__ == "__main__":
    sys.exit(main())
