#!/usr/bin/env bash
# test_graph.sh — end-to-end test for the two-pass graph layer (#221).
#
# Asserts:
#   1. Pre-migration probe: build_graph.py hard-fails on the legacy fixture.
#   2. Pass-1 edge count: known fixture yields exactly 5 EXTRACTED edges.
#   3. Self-loop & dangling-link exclusion: looper page contributes 0 edges.
#   4. Self-contained HTML: zero external URLs in the rendered output.
#   5. Idempotency: two runs produce identical bytes (modulo timestamp).
#   6. Cache hit on re-enumerate: recording a judgement removes that pair
#      from the next candidate enumeration.
#   7. Stale-cache invalidation: modifying a page body re-surfaces its pairs.
#   8. Community count: ≥ 2 communities for a graph with multiple components.
#
# bash 3.2 + python3 stdlib only. Exits non-zero on any failure.

set -eu

PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FIXTURES="$PLUGIN_ROOT/tests/fixtures"
SCRIPT="$PLUGIN_ROOT/skills/wiki-dashboard/scripts/build_graph.py"

WORKDIR="$(mktemp -d)"
WIKI="$WORKDIR/graph-wiki"

cleanup() { rm -rf "$WORKDIR"; }
trap cleanup EXIT

red() { printf '\033[31m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }

fail() { red "FAIL: $1"; exit 1; }

assert_success_json() {
  local label="$1" out="$2" ok
  ok=$(printf '%s' "$out" | python3 -c 'import json,sys
d=json.loads(sys.stdin.read()); print("yes" if d.get("success") else "no")' 2>/dev/null || echo "parse-error")
  [ "$ok" = "yes" ] || { red "FAIL ($label): expected success:true"; printf '%s\n' "$out"; exit 1; }
}

assert_failure_with_migration_msg() {
  local label="$1" out="$2" result
  result=$(printf '%s' "$out" | python3 -c 'import json,sys
d=json.loads(sys.stdin.read())
print("ok" if (not d.get("success")) and ("pre-migration" in d.get("error","")) else "bad")' 2>/dev/null || echo "parse-error")
  [ "$result" = "ok" ] || { red "FAIL ($label): expected pre-migration failure"; printf '%s\n' "$out"; exit 1; }
}

json_field() {
  # $1 = json, $2 = dotted path (e.g. "data.count")
  printf '%s' "$1" | python3 -c "
import json,sys
d=json.loads(sys.stdin.read())
for k in '$2'.split('.'):
    d=d[k] if isinstance(d,dict) else d[int(k)]
print(d)
"
}

# ---------- 1) pre-migration probe ----------
green "1) pre-migration probe"
OUT=$(python3 "$SCRIPT" --wiki-root "$FIXTURES/legacy-wiki" --output "$WORKDIR/x.html" 2>/dev/null || true)
assert_failure_with_migration_msg "pre-migration probe" "$OUT"

# ---------- copy fixture ----------
cp -R "$FIXTURES/graph-wiki" "$WIKI"

# ---------- 2) Pass-1 edge count ----------
green "2) pass-1 edge count"
OUT=$(python3 "$SCRIPT" --wiki-root "$WIKI" --output "$WIKI/wiki-graph.html")
assert_success_json "build" "$OUT"
COUNT=$(json_field "$OUT" "data.edges_pass1")
[ "$COUNT" = "5" ] || fail "expected 5 EXTRACTED edges, got $COUNT"

# ---------- 3) self-loop & dangling-link exclusion ----------
green "3) self-loop and dangling-link exclusion"
# Looper has [[looper]] (self) and [[ghost-slug]] (dangling). Neither must produce an edge.
LOOPER_EDGES=$(python3 -c "
import re,sys
text = open('$WIKI/wiki-graph.html').read()
import json
m = re.search(r'const GRAPH = (\{.*?\});\\n', text)
g = json.loads(m.group(1))
edges_from_looper = [e for e in g['edges'] if e['from']=='looper' or e['to']=='looper']
print(len(edges_from_looper))
")
[ "$LOOPER_EDGES" = "0" ] || fail "expected 0 edges touching looper, got $LOOPER_EDGES"

# ---------- 4) self-contained HTML (no external URLs) ----------
green "4) self-contained HTML"
EXT_REFS=$(grep -cE 'https?://|cdn\.|unpkg\.|jsdelivr|googleapis' "$WIKI/wiki-graph.html" || true)
[ "$EXT_REFS" = "0" ] || fail "expected 0 external URLs in HTML, found $EXT_REFS"

# ---------- 5) idempotency ----------
green "5) idempotency"
python3 "$SCRIPT" --wiki-root "$WIKI" --output "$WORKDIR/run1.html" >/dev/null
python3 "$SCRIPT" --wiki-root "$WIKI" --output "$WORKDIR/run2.html" >/dev/null
DIFF=$(diff <(sed -E 's/Generated by cogni-wiki v[0-9.]+ · [0-9-]+ [0-9:]+/X/' "$WORKDIR/run1.html") \
            <(sed -E 's/Generated by cogni-wiki v[0-9.]+ · [0-9-]+ [0-9:]+/X/' "$WORKDIR/run2.html") || true)
[ -z "$DIFF" ] || fail "non-idempotent output (diff non-empty)"

# ---------- 6) cache hit on re-enumerate ----------
green "6) cache hit on re-enumerate"
OUT=$(python3 "$SCRIPT" --wiki-root "$WIKI" --mode enumerate-candidates)
assert_success_json "enumerate-1" "$OUT"
INITIAL=$(json_field "$OUT" "data.count")
[ "$INITIAL" -ge "1" ] || fail "expected ≥ 1 candidate, got $INITIAL"

PAIR_INFO=$(printf '%s' "$OUT" | python3 -c '
import json,sys
d=json.loads(sys.stdin.read())
c=d["data"]["candidates"][0]
print(c["pair_id"], c["slug_a"], c["slug_b"])
')
PID=$(echo "$PAIR_INFO" | awk '{print $1}')
SA=$(echo "$PAIR_INFO" | awk '{print $2}')
SB=$(echo "$PAIR_INFO" | awk '{print $3}')

OUT=$(python3 "$SCRIPT" --wiki-root "$WIKI" --mode record-judgement \
  --pair-id "$PID" --slug-a "$SA" --slug-b "$SB" \
  --judgement related --confidence 0.85 --relationship "test fixture")
assert_success_json "record-judgement" "$OUT"

OUT=$(python3 "$SCRIPT" --wiki-root "$WIKI" --mode enumerate-candidates)
AFTER=$(json_field "$OUT" "data.count")
EXPECTED=$((INITIAL - 1))
[ "$AFTER" = "$EXPECTED" ] || fail "expected $EXPECTED candidates after record, got $AFTER"

# Verify Pass-2 edge surfaces in build output.
OUT=$(python3 "$SCRIPT" --wiki-root "$WIKI" --output "$WIKI/wiki-graph.html")
P2=$(json_field "$OUT" "data.edges_pass2")
[ "$P2" = "1" ] || fail "expected 1 INFERRED edge after build, got $P2"

# ---------- 7) stale-cache invalidation ----------
green "7) stale-cache invalidation"
# Mutate the page that was part of the recorded pair → cache hash mismatch → pair returns to candidates.
echo "" >> "$WIKI/wiki/concepts/$SA.md"
echo "Additional content for hash invalidation." >> "$WIKI/wiki/concepts/$SA.md"
OUT=$(python3 "$SCRIPT" --wiki-root "$WIKI" --mode enumerate-candidates)
STALE=$(json_field "$OUT" "data.count")
[ "$STALE" = "$INITIAL" ] || fail "expected stale-invalidation to resurface pair (initial=$INITIAL, got $STALE)"

# ---------- 8) community count ----------
green "8) community count"
OUT=$(python3 "$SCRIPT" --wiki-root "$WIKI" --output "$WIKI/wiki-graph.html")
COMMS=$(json_field "$OUT" "data.communities")
[ "$COMMS" -ge "2" ] || fail "expected ≥ 2 communities, got $COMMS"

green "ALL 8 TESTS PASSED"
