#!/usr/bin/env bash
# generate-settings.sh - Generate .claude/settings.local.json and .workspace-env.sh
# Usage: generate-settings.sh --target <dir> --language <en|de> --plugins <json-file-or-string>
# Optional: --update (preserve custom env vars)

set -euo pipefail

SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"

# Parse arguments
TARGET_DIR=""
LANGUAGE="en"
PLUGINS_ARG="[]"
UPDATE_MODE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target) TARGET_DIR="$2"; shift 2 ;;
    --language) LANGUAGE="$2"; shift 2 ;;
    --plugins) PLUGINS_ARG="$2"; shift 2 ;;
    --update) UPDATE_MODE=true; shift ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$TARGET_DIR" ]; then
  echo '{"success":false,"data":{"error":"--target is required"}}' >&2
  exit 2
fi

# Resolve plugins JSON: if it's a file path, read it; otherwise treat as inline JSON
PLUGINS_TMPFILE=$(mktemp)
trap 'rm -f "$PLUGINS_TMPFILE"' EXIT

if [ -f "$PLUGINS_ARG" ]; then
  cp "$PLUGINS_ARG" "$PLUGINS_TMPFILE"
else
  echo "$PLUGINS_ARG" > "$PLUGINS_TMPFILE"
fi

# Create directories
mkdir -p "${TARGET_DIR}/.claude"
mkdir -p "${TARGET_DIR}/cogni-workspace/themes"

TARGET_ABS=$(cd "$TARGET_DIR" && pwd)

# Generate all config files via single Python call
python3 << PYEOF
import json, os, sys
from datetime import datetime, timezone

target = "$TARGET_ABS"
language = "$LANGUAGE"
update_mode = $( [ "$UPDATE_MODE" = true ] && echo "True" || echo "False" )

with open("$PLUGINS_TMPFILE") as f:
    plugins = json.load(f)

# Build env vars
env = {}
env["PROJECT_AGENTS_OPS_ROOT"] = target
env["COGNI_WORKSPACE_ROOT"] = os.path.join(target, "cogni-workspace")

for p in plugins:
    name = p.get("name", "") if isinstance(p, dict) else p
    path = p.get("path", "") if isinstance(p, dict) else ""

    if name.startswith("cogni-"):
        suffix = name.replace("cogni-", "").upper().replace("-", "_")
        root_var = f"COGNI_{suffix}_ROOT"
        plugin_var = f"COGNI_{suffix}_PLUGIN"
    else:
        suffix = name.upper().replace("-", "_")
        root_var = f"PLUGIN_{suffix}_ROOT"
        plugin_var = f"PLUGIN_{suffix}_PLUGIN"

    env[root_var] = os.path.join(target, name)
    if path:
        env[plugin_var] = path

# Merge with existing custom vars if update mode
settings_path = os.path.join(target, ".claude", "settings.local.json")
if update_mode and os.path.isfile(settings_path):
    with open(settings_path) as f:
        existing = json.load(f)
    for k, v in existing.get("env", {}).items():
        if k not in env:
            env[k] = v

# Write settings.local.json
with open(settings_path, "w") as f:
    json.dump({"env": env}, f, indent=2)
    f.write("\n")

# Write .workspace-env.sh
env_sh_path = os.path.join(target, ".workspace-env.sh")
lines = [
    "#!/usr/bin/env bash",
    "# Auto-generated by cogni-workspace. Do not edit manually.",
    "# Source this file in non-Claude contexts (Obsidian Terminal, VS Code, CI/CD)",
    ""
]
for k, v in sorted(env.items()):
    lines.append(f'export {k}="{v}"')
lines.append("")
with open(env_sh_path, "w") as f:
    f.write("\n".join(lines))

# Write .workspace-config.json
config_path = os.path.join(target, ".workspace-config.json")
plugin_names = sorted([p.get("name", p) if isinstance(p, dict) else p for p in plugins])

if update_mode and os.path.isfile(config_path):
    with open(config_path) as f:
        config = json.load(f)
    config["installed_plugins"] = plugin_names
    config["updated_at"] = datetime.now(timezone.utc).isoformat()
    config["language"] = language
else:
    config = {
        "version": "0.1.0",
        "language": language,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat(),
        "installed_plugins": plugin_names,
        "tool_integrations": []
    }

with open(config_path, "w") as f:
    json.dump(config, f, indent=2)
    f.write("\n")

# Create plugin data directories
for p in plugins:
    name = p.get("name", p) if isinstance(p, dict) else p
    os.makedirs(os.path.join(target, name), exist_ok=True)

# Output result
result = {
    "success": True,
    "data": {
        "target": target,
        "language": language,
        "env_vars_count": len(env),
        "files_written": [
            ".claude/settings.local.json",
            ".workspace-env.sh",
            ".workspace-config.json"
        ],
        "update_mode": update_mode
    },
    "metadata": {
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "script": "$SCRIPT_NAME",
        "version": "0.1.0"
    }
}
print(json.dumps(result, indent=2))
PYEOF
